# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json

gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  border: "rounded"
  theme:
    activeBorderColor:
      - "#fab387"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#fab387"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
os:
  edit: "$EDITOR {{filename}}"
customCommands:
  - key: "H"
    context: "files"
    description: "Review working tree in hunk"
    command: "hunk diff"
    output: terminal
  - key: "H"
    context: "commits"
    description: "Review commit in hunk"
    command: "hunk show {{.SelectedLocalCommit.Hash}}"
    output: terminal
