return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    plugins = { spelling = true },
    spec = {
      { "<leader>a", group = "AI", icon = "" },
      { "<leader>b", group = "Buffer" },
      { "<leader>c", group = "Code" },
      { "<leader>d", group = "Debug" },
      { "<leader>f", group = "File/Find" },
      { "<leader>g", group = "Git" },
      { "<leader>h", group = "Harpoon", icon = "󱡅" },
      { "<leader>o", group = "Obsidian", icon = "󱞁" },
      { "<leader>q", group = "Quit/Session" },
      { "<leader>s", group = "Search" },
      { "<leader>t", group = "Test" },
      { "<leader>u", group = "UI" },
      { "<leader>x", group = "Diagnostics/Quickfix" },
      { "[", group = "Prev" },
      { "]", group = "Next" },
      { "g", group = "Goto" },
      { "gs", group = "Surround" },
      { "z", group = "Fold" },
      { "<leader>w", desc = "Save", icon = "󰈔" },
      { "<leader>S", desc = "Reload Snippets", icon = "" },
      { "<leader><tab>", hidden = true },
      { "<leader>-", hidden = true },
      { "<leader>|", hidden = true },
    },
  },
}
